version: '3.9'
services:
  backend:
    restart: always
    container_name: kupipodariday-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: kupipodariday-backend-opti
    ports:
      - 4000:4000
    env_file:
      - .env
    networks:
      - backend

  frontend:
    container_name: kupipodariday-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kupipodariday-frontend-opti
    ports: # Внутри контейнера процесс будет работать на 80-м порту (из-за nginx)
      - 5005:80
    networks:
      - frontend

  postgres:
    restart: always
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend: 
